# Generated by Django 3.1 on 2021-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='ques_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'CHOICE'), (3, 'MULTI CHOICE')], default=0),
        ),
    ]
