# Generated by Django 3.1 on 2021-07-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0012_auto_20210701_1820'),
        ('client', '0008_syrveyresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SyrveyResponse',
            new_name='SurveyResponse',
        ),
    ]
