# Generated by Django 3.1 on 2021-06-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_auto_20210625_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client_name',
            new_name='name',
        ),
    ]
