# Generated by Django 3.1 on 2021-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0004_auto_20210625_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
