# Generated by Django 3.1 on 2021-06-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0010_auto_20210625_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Clients'},
        ),
    ]
