# Generated by Django 3.1 on 2021-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0011_auto_20210628_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestionchoice',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='surveyquestionchoice',
            name='ques_id',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.DeleteModel(
            name='SurveyQuestionChoice',
        ),
    ]
