# Generated by Django 3.1 on 2021-07-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210702_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='ques_type',
            field=models.IntegerField(choices=[(1, 'TEXT'), (2, 'CHOICE'), (3, 'MULTI CHOICE')], default=1),
        ),
    ]
